// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.18.0
// source: stateless_block.go

package chain

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__Block__Prnt         = 1
	canoto__Block__Tmstmp       = 2
	canoto__Block__Hght         = 3
	canoto__Block__BlockContext = 4
	canoto__Block__Txs          = 5
	canoto__Block__StateRoot    = 6

	canoto__Block__Prnt__tag         = "\x0a" // canoto.Tag(canoto__Block__Prnt, canoto.Len)
	canoto__Block__Tmstmp__tag       = "\x11" // canoto.Tag(canoto__Block__Tmstmp, canoto.I64)
	canoto__Block__Hght__tag         = "\x19" // canoto.Tag(canoto__Block__Hght, canoto.I64)
	canoto__Block__BlockContext__tag = "\x22" // canoto.Tag(canoto__Block__BlockContext, canoto.Len)
	canoto__Block__Txs__tag          = "\x2a" // canoto.Tag(canoto__Block__Txs, canoto.Len)
	canoto__Block__StateRoot__tag    = "\x32" // canoto.Tag(canoto__Block__StateRoot, canoto.Len)
)

type canotoData_Block struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*Block) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeFor[Block]())
	var zero Block
	s := &canoto.Spec{
		Name: "Block",
		Fields: []canoto.FieldType{
			{
				FieldNumber:    canoto__Block__Prnt,
				Name:           "Prnt",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.Prnt)),
			},
			canoto.FieldTypeFromFint(
				/*type inference:*/ zero.Tmstmp,
				/*FieldNumber:   */ canoto__Block__Tmstmp,
				/*Name:          */ "Tmstmp",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
			),
			canoto.FieldTypeFromFint(
				/*type inference:*/ zero.Hght,
				/*FieldNumber:   */ canoto__Block__Hght,
				/*Name:          */ "Hght",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
			),
			canoto.FieldTypeFromField(
				/*type inference:*/ (zero.BlockContext),
				/*FieldNumber:   */ canoto__Block__BlockContext,
				/*Name:          */ "BlockContext",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*Pointer:       */ true,
				/*types:         */ types,
			),
			canoto.FieldTypeFromField(
				/*type inference:*/ (canoto.MakeEntry(zero.Txs)),
				/*FieldNumber:   */ canoto__Block__Txs,
				/*Name:          */ "Txs",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*Pointer:       */ true,
				/*types:         */ types,
			),
			{
				FieldNumber:    canoto__Block__StateRoot,
				Name:           "StateRoot",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.StateRoot)),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *Block) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *Block) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = Block{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__Block__Prnt:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.Prnt)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.Prnt)[:], r.B)
			if canoto.IsZero(c.Prnt) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case canoto__Block__Tmstmp:
			if wireType != canoto.I64 {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadFint64(&r, &c.Tmstmp); err != nil {
				return err
			}
			if canoto.IsZero(c.Tmstmp) {
				return canoto.ErrZeroValue
			}
		case canoto__Block__Hght:
			if wireType != canoto.I64 {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadFint64(&r, &c.Hght); err != nil {
				return err
			}
			if canoto.IsZero(c.Hght) {
				return canoto.ErrZeroValue
			}
		case canoto__Block__BlockContext:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.BlockContext = canoto.MakePointer(c.BlockContext)
			if err := (c.BlockContext).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		case canoto__Block__Txs:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canoto__Block__Txs__tag)
			if err != nil {
				return err
			}

			c.Txs = canoto.MakeSlice(c.Txs, countMinus1+1)
			field := c.Txs
			additionalField := field[1:]
			if len(msgBytes) != 0 {
				innerBytes, err := canoto.ReadPointerPresence(msgBytes)
				if err != nil {
					return err
				}
				remainingBytes := r.B
				r.B = innerBytes
				field[0] = canoto.MakePointer(field[0])
				if err := (field[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range additionalField {
				r.B = r.B[len(canoto__Block__Txs__tag):]
				r.Unsafe = true
				if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				r.Unsafe = originalUnsafe
				if len(msgBytes) == 0 {
					continue
				}

				innerBytes, err := canoto.ReadPointerPresence(msgBytes)
				if err != nil {
					return err
				}
				remainingBytes := r.B
				r.B = innerBytes
				additionalField[i] = canoto.MakePointer(additionalField[i])
				if err := (additionalField[i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		case canoto__Block__StateRoot:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.StateRoot)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.StateRoot)[:], r.B)
			if canoto.IsZero(c.StateRoot) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *Block) ValidCanoto() bool {
	if c.BlockContext != nil && !(c.BlockContext).ValidCanoto() {
		return false
	}
	{
		field := c.Txs
		for i := range field {
			if field[i] != nil && !(field[i]).ValidCanoto() {
				return false
			}
		}
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *Block) CalculateCanotoCache() {
	var size uint64
	if !canoto.IsZero(c.Prnt) {
		size += uint64(len(canoto__Block__Prnt__tag)) + canoto.SizeBytes((&c.Prnt)[:])
	}
	if !canoto.IsZero(c.Tmstmp) {
		size += uint64(len(canoto__Block__Tmstmp__tag)) + canoto.SizeFint64
	}
	if !canoto.IsZero(c.Hght) {
		size += uint64(len(canoto__Block__Hght__tag)) + canoto.SizeFint64
	}
	if c.BlockContext != nil {
		(c.BlockContext).CalculateCanotoCache()
		fieldSize := (c.BlockContext).CachedCanotoSize()
		size += uint64(len(canoto__Block__BlockContext__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	{
		field := c.Txs
		for i := range field {
			var fieldSize uint64
			if field[i] != nil {
				(field[i]).CalculateCanotoCache()
				innerSize := (field[i]).CachedCanotoSize()
				fieldSize = canoto.SizePointerPresenceTag + canoto.SizeUint(innerSize) + innerSize
			}
			size += uint64(len(canoto__Block__Txs__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		}
	}
	if !canoto.IsZero(c.StateRoot) {
		size += uint64(len(canoto__Block__StateRoot__tag)) + canoto.SizeBytes((&c.StateRoot)[:])
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *Block) CachedCanotoSize() uint64 {
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *Block) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *Block) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if !canoto.IsZero(c.Prnt) {
		canoto.Append(&w, canoto__Block__Prnt__tag)
		canoto.AppendBytes(&w, (&c.Prnt)[:])
	}
	if !canoto.IsZero(c.Tmstmp) {
		canoto.Append(&w, canoto__Block__Tmstmp__tag)
		canoto.AppendFint64(&w, c.Tmstmp)
	}
	if !canoto.IsZero(c.Hght) {
		canoto.Append(&w, canoto__Block__Hght__tag)
		canoto.AppendFint64(&w, c.Hght)
	}
	if c.BlockContext != nil {
		fieldSize := (c.BlockContext).CachedCanotoSize()
		canoto.Append(&w, canoto__Block__BlockContext__tag)
		canoto.AppendUint(&w, fieldSize)
		w = (c.BlockContext).MarshalCanotoInto(w)
	}
	{
		field := c.Txs
		for i := range field {
			canoto.Append(&w, canoto__Block__Txs__tag)
			if field[i] == nil {
				canoto.Append(&w, canoto.EmptyBytes)
			} else {
				innerSize := (field[i]).CachedCanotoSize()
				fieldSize := canoto.SizePointerPresenceTag + canoto.SizeUint(innerSize) + innerSize
				canoto.AppendUint(&w, fieldSize)
				canoto.Append(&w, canoto.PointerPresenceTag)
				canoto.AppendUint(&w, innerSize)
				w = (field[i]).MarshalCanotoInto(w)
			}
		}
	}
	if !canoto.IsZero(c.StateRoot) {
		canoto.Append(&w, canoto__Block__StateRoot__tag)
		canoto.AppendBytes(&w, (&c.StateRoot)[:])
	}
	return w
}
