// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.18.0
// source: transaction_marshaller.go

package chain

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__BatchedTransactions__Transactions = 1

	canoto__BatchedTransactions__Transactions__tag = "\x0a" // canoto.Tag(canoto__BatchedTransactions__Transactions, canoto.Len)
)

type canotoData_BatchedTransactions struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*BatchedTransactions) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeFor[BatchedTransactions]())
	var zero BatchedTransactions
	s := &canoto.Spec{
		Name: "BatchedTransactions",
		Fields: []canoto.FieldType{
			canoto.FieldTypeFromField(
				/*type inference:*/ (canoto.MakeEntry(zero.Transactions)),
				/*FieldNumber:   */ canoto__BatchedTransactions__Transactions,
				/*Name:          */ "Transactions",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*Pointer:       */ true,
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *BatchedTransactions) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *BatchedTransactions) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = BatchedTransactions{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__BatchedTransactions__Transactions:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canoto__BatchedTransactions__Transactions__tag)
			if err != nil {
				return err
			}

			c.Transactions = canoto.MakeSlice(c.Transactions, countMinus1+1)
			field := c.Transactions
			additionalField := field[1:]
			if len(msgBytes) != 0 {
				innerBytes, err := canoto.ReadPointerPresence(msgBytes)
				if err != nil {
					return err
				}
				remainingBytes := r.B
				r.B = innerBytes
				field[0] = canoto.MakePointer(field[0])
				if err := (field[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range additionalField {
				r.B = r.B[len(canoto__BatchedTransactions__Transactions__tag):]
				r.Unsafe = true
				if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				r.Unsafe = originalUnsafe
				if len(msgBytes) == 0 {
					continue
				}

				innerBytes, err := canoto.ReadPointerPresence(msgBytes)
				if err != nil {
					return err
				}
				remainingBytes := r.B
				r.B = innerBytes
				additionalField[i] = canoto.MakePointer(additionalField[i])
				if err := (additionalField[i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *BatchedTransactions) ValidCanoto() bool {
	{
		field := c.Transactions
		for i := range field {
			if field[i] != nil && !(field[i]).ValidCanoto() {
				return false
			}
		}
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *BatchedTransactions) CalculateCanotoCache() {
	var size uint64
	{
		field := c.Transactions
		for i := range field {
			var fieldSize uint64
			if field[i] != nil {
				(field[i]).CalculateCanotoCache()
				innerSize := (field[i]).CachedCanotoSize()
				fieldSize = canoto.SizePointerPresenceTag + canoto.SizeUint(innerSize) + innerSize
			}
			size += uint64(len(canoto__BatchedTransactions__Transactions__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		}
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *BatchedTransactions) CachedCanotoSize() uint64 {
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *BatchedTransactions) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *BatchedTransactions) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	{
		field := c.Transactions
		for i := range field {
			canoto.Append(&w, canoto__BatchedTransactions__Transactions__tag)
			if field[i] == nil {
				canoto.Append(&w, canoto.EmptyBytes)
			} else {
				innerSize := (field[i]).CachedCanotoSize()
				fieldSize := canoto.SizePointerPresenceTag + canoto.SizeUint(innerSize) + innerSize
				canoto.AppendUint(&w, fieldSize)
				canoto.Append(&w, canoto.PointerPresenceTag)
				canoto.AppendUint(&w, innerSize)
				w = (field[i]).MarshalCanotoInto(w)
			}
		}
	}
	return w
}
